apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: staging
spec:
  selector:
    matchLabels:
      app: cast-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: patrick35/cast-service:20231226
        ports:
        - containerPort: 8000
