apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-devops-exams.fullname" . }}
  labels:
    {{- include "jenkins-devops-exams.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "jenkins-devops-exams.selectorLabels" . | nindent 4 }}
